### ISSUE TITLE
Virgo crashes on startup win10

### ISSUE THREAD

**Issue by hwine** [MozillaSecurity/virgo#12]
- **Version**:  0.2.1
- **Platform**:  Windows 10 version 1903 (OS Build 18362.207)

Launching yields a crash dialog:
![image](https://user-images.githubusercontent.com/132412/60747669-b8926700-9f3b-11e9-8519-fec370d450dc.png)

After clicking OK, the dashboard comes up, but nothing seems to happen there. In Task Manager, 3 processes are running:
![image](https://user-images.githubusercontent.com/132412/60747705-1aeb6780-9f3c-11e9-8adf-e9e5dbde1d70.png)

Note: I do have Docker configured to expose the daemon on tcp://localhost:2375 without tls, so that I can use it from WSL.

**Comment by posidron** [comment]
Thanks Hal for testing! I'm gonna look into this next week. I assume it's because in this situation the  default used Windows socketPath for Docker `//./pipe/docker_engine` is not valid anymore and we don't bail out on that early enough. Fix should be easy but need to think about how to detect such custom Daemon setups for the launch.

**Comment by posidron** [comment]
Okay, possible solution would be: Launch the UI, let the renderer send an IPC message to main for initiating a connection to the Docker engine. If failed on N times, do nothing. Let user adjust engine connection settings in the preferences.

**Comment by posidron** [comment]
This should be fixed (tested), please try again. It was not related to the above but due to `setAboutPanelOptions` being not available on Windows. 

Download: https://github.com/MozillaSecurity/virgo/releases/download/v0.2.2/virgo-0.2.2-win.exe

You probably have already done so but just in case make sure that you enabled the volume  in `Settings -> Shared Drives` on which you have installed Virgo. This seems to be an explicit requirement on Windows before allowing to mount volumes.

Before launching please run: `rm ~\AppData\Roaming\virgo\config.json` to have a clean start.

**Comment by hwine** [comment]
> This should be fixed (tested), please try again. It was not related to the above but due to `setAboutPanelOptions` being not available on Windows.
> 
> Download: https://github.com/MozillaSecurity/virgo/releases/download/v0.2.2/virgo-0.2.2-win.exe

Starts up (no crashes) and has downloaded the image. No container has started yet.
 
> You probably have already done so but just in case make sure that you enabled the volume in Docker preferences `Settings -> Shared Drives` on which you have installed Virgo. This seems to be an explicit requirement on Windows before allowing to mount volumes.

I don't have any such setting in Docker -- but I also only have one drive. No explicit error messages anywhere I can see. I can mount volumes fine in my day-to-day usage.

> Before launching please run: `rm ~\AppData\Roaming\virgo\config.json` to have a clean start.

:heavy_check_mark:

**Comment by posidron** [comment]
> Starts up (no crashes) and has downloaded the image. No container has started yet.

> I don't have any such setting in Docker -- but I also only have one drive. No explicit error messages anywhere I can see. I can mount volumes fine in my day-to-day usage.

![Screen Shot 2019-07-07 at 6 29 31 AM](https://user-images.githubusercontent.com/1614333/60764010-ea611600-a080-11e9-8cad-73aa925c5d12.png)

This was required for me on Windows to mount files into a container (which is in our case the FuzzManager backend configuration). If this fails to mount, the container will abort.

The necessity could be an issue cause by the Docker API bridge vs. the default docker cli. Which Docker version are you using on Windows and Enterprise or CE?

If this still fails, I please you to do factory reset, launch Virgo from the command line, initiate a run in the App and past me the output from the Terminal.

**Comment by hwine** [comment]
Current docker version: Version 2.0.0.3 (31259) (CE on Windows 10)

My settings screen doesn't have anything about shared drives, but I do use that feature all the time from WSL:
![image](https://user-images.githubusercontent.com/132412/60821928-5b73fc80-a159-11e9-9dbc-a7b24fdad6bd.png)

I reset docker, started virgo from command line, hit the play button, and got
```C:\Program Files\Virgo>
 Initializing DockerManager for Platform: win32
{"msg":"≡ƒûÑ App version: 0.2.2"}
08:46:12.764 > Checking for update
{"msg":"≡ƒöÄ Checking for updates ..."}
08:46:15.481 > Update for version 0.2.2 is not available (latest version: 0.2.2, downgrade is disallowed).
{"msg":"≡ƒæÄ Update not available."}
PULL error in onFinished.
Image error: "image operating system \"linux\" cannot be used on this platform"
```

I'm puzzled by the last message, as I _only_ use linux containers. I do use the linux docker client in WSL, but the docker daemon is the windows one.

Unlike my first successful startup, no image has been downloaded. (The docker reset removes all existing images and containers.)

**Comment by posidron** [comment]
Ah, I have a guess here. Can you verify that you actually run Docker on Windows to run Linux containers instead of Windows containers. You can see that by right click on the Docker icon in your Taskbar.

![Screen Shot 2019-07-08 at 7 16 27 PM](https://user-images.githubusercontent.com/1614333/60829312-e9310580-a1b4-11e9-83ff-06fb1458c52d.png)
(Runs Linux containers on Windows)

Because I think the UI of Docker which you showed, is only visible if Docker is in the mode to run Windows containers on Windows.

**Comment by hwine** [comment]
You're right, @posidron  - after resetting docker, it was back to windows containers. I switched to linux containers, and got the "do you want to share drive c:" message. _[I didn't remember ever setting linux containers -- I'll add that to my notes before I get stuck in the future.]_

Everything appears to be running okay now -- an image was pulled, and a container is running! 🎉 

**Question:** does this mean that, while my machine has windows, it is only fuzzing linux builds? If so, I'll likely drop out, as I have a wimpy machine, but suspected there wouldn't be many win10 folks interested.

**Comment by posidron** [comment]
Awesome! 

I will also add this to the docs, because after some time while experimenting/working on it I also forgot which settings are default and which not.

It seems to be possible to use `docker run --platform=linux ...` to run Linux containers on Windows while having Windows containers enabled in Docker. I guess I need to look in implementing that feature.

Source: https://devblogs.microsoft.com/premier-developer/running-docker-windows-and-linux-containers-simultaneously/

We have no Window containers available yet in [Orion](https://github.com/MozillaSecurity/orion/) which are build automatically. It's in planning though. So, yes, you are fuzzing now solely LibFuzzer/Firefox inside of a Linux container.

That's fine for now. CPU/RAM constraints are still in the works but planned for end of H2, same as having a scheduler managing the start&pause automatically for you.

Thanks for testing it on Windows. Closing the issue as resolved.
